# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6aa058854217b7ed17bc53d64cd55a5c4c69eee270090f20599fc171a400ca044ab6ee250160c0edb42945c6bf21e9e001b9a25b84a48c9b0b385c23cec931f6

test:
  secret_key_base: 64e10eb4910b8e6f5971340cbdeb55dc67bffba08bb0b56208ef2ac514bfbb14520c202189fb09153d9f0365e7afbcaa19247d76b50dc3dd042e270dd40fd959

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
